#!/bin/bash
<<<<<<< HEAD
if [[ ! -e "$HOME"/.config/osc/oscrc ]]
then
echo '[general]' > oscrc
echo 'apiurl=https://api.opensuse.org' >> oscrc
echo '[https://api.opensuse.org]' >> oscrc
echo "user=${OBS_USER}" >> oscrc
echo "pass=${OBS_PASSWORD}" >> oscrc
echo 'credentials_mgr_class=osc.credentials.ObfuscatedConfigFileCredentialsManager' >> oscrc

install -Dm644 oscrc "$HOME"/.config/osc/oscrc
fi


=======
shopt -s extglob
shopt -s globstar

if [[ ! -e "$HOME"/.config/osc/oscrc ]]
then

mkdir -p "$HOME"/.config/osc ||:

cat << EFO > "$HOME"/.config/osc/oscrc
[general]
apiurl=https://api.opensuse.org

[https://api.opensuse.org]
user=${OBS_USERNAME}
pass=${OBS_PASSWORD}
credentials_mgr_class=osc.credentials.ObfuscatedConfigFileCredentialsManager
EFO

fi

>>>>>>> other-repo/main
. PKGBUILD
mkdir nekobox_temp
pushd nekobox_temp

pkgurl="$(echo ${source[0]} | sed "s@$pkgver@%{version}@g;" )"

osc co home:juzbun:NekoBox/nekobox -o nekobox
osc co network:vpn/nekobox -o nekobox_tumbleweed

(
cd nekobox
echo "$pkgver" > version.txt
osc addremove
osc ci -m update
)

(
cd nekobox_tumbleweed
<<<<<<< HEAD
rm *.tar.xz
rm nekobox.spec
=======
osc update
rm !(nekobox.changes)
>>>>>>> other-repo/main

wget https://codefloe.com/qr243vbi/nekobox/raw/branch/main/nekobox.spec

sed -i "s@Source0:.*@Source0: $pkgurl@g; s@Version:.*@Version: $pkgver@g;" nekobox.spec

<<<<<<< HEAD
wget "${source[0]}"
=======
source_0="${source[0]}"
if [[ ! -f `basename "${source_0}"` ]]
then
  wget -c "${source_0}"
fi
>>>>>>> other-repo/main
osc addremove
python -c "
import os
text = ''
if os.path.exists('nekobox.changes'):
 f=open('nekobox.changes', 'r')
 text=f.read()
 f.close()
msg='$MESSAGE'
import textwrap
if len(msg) > 0 and 'Update to $INPUT_VERSION' not in text:
 msg = textwrap.fill(msg, 65)
 if msg[-1] != '\n':
  msg = msg + '\n'
 k='-------------------------------------------------------------------'
 k+='\n$(date) - bunny bn <g89156436@gmail.com>\n\n'
 k+='Update to $INPUT_VERSION\n' + msg + '\n' 
 text=k+text
 f=open('nekobox.changes', 'w')
 f.write(text)
 f.close()
<<<<<<< HEAD
print(text)"

osc ci -m update 

if [[ "$SUBMIT_FACTORY" == 'true' ]]
then
osc sr openSUSE:Factory nekobox --message "Update to $INPUT_VERSION. $MESSAGE. Generated by Github Actions."
=======
print(text)
"
osc rm _meta
rm _meta
osc addremove 
osc ci -m "$MESSAGE. Generated by Github Actions" 

if [[ "$SUBMIT_FACTORY" == 'true' ]]
then
osc sr --yes openSUSE:Factory nekobox --message "Update to $INPUT_VERSION. $MESSAGE. Generated by Github Actions."
>>>>>>> other-repo/main
fi

)


popd
