#!/bin/bash
if [[ ! -e "$HOME"/.config/osc/oscrc ]]
then
echo '[general]' > oscrc
echo 'apiurl=https://api.opensuse.org' >> oscrc
echo '[https://api.opensuse.org]' >> oscrc
echo "user=${OBS_USER}" >> oscrc
echo "pass=${OBS_PASSWORD}" >> oscrc
echo 'credentials_mgr_class=osc.credentials.ObfuscatedConfigFileCredentialsManager' >> oscrc

install -Dm644 oscrc "$HOME"/.config/osc/oscrc
fi


. PKGBUILD
mkdir nekobox_temp
pushd nekobox_temp

pkgurl="$(echo ${source[0]} | sed "s@$pkgver@%{version}@g;" )"

osc co home:juzbun:NekoBox/nekobox -o nekobox
osc co network:vpn/nekobox -o nekobox_tumbleweed

(
cd nekobox
echo "$pkgver" > version.txt
osc addremove
osc ci -m update
)

(
cd nekobox_tumbleweed
rm *.tar.xz
rm nekobox.spec

wget https://codefloe.com/qr243vbi/nekobox/raw/branch/main/nekobox.spec

sed -i "s@Source0:.*@Source0: $pkgurl@g; s@Version:.*@Version: $pkgver@g;" nekobox.spec

wget "${source[0]}"
osc addremove
python -c "
import os
text = ''
if os.path.exists('nekobox.changes'):
 f=open('nekobox.changes', 'r')
 text=f.read()
 f.close()
msg='$MESSAGE'
import textwrap
if len(msg) > 0 and 'Update to $INPUT_VERSION' not in text:
 msg = textwrap.fill(msg, 65)
 if msg[-1] != '\n':
  msg = msg + '\n'
 k='-------------------------------------------------------------------'
 k+='\n$(date) - bunny bn <g89156436@gmail.com>\n\n'
 k+='Update to $INPUT_VERSION\n' + msg + '\n' 
 text=k+text
 f=open('nekobox.changes', 'w')
 f.write(text)
 f.close()
print(text)"

osc ci -m update 

if [[ "$SUBMIT_FACTORY" == 'true' ]]
then
osc sr openSUSE:Factory nekobox --message "Update to $INPUT_VERSION. $MESSAGE. Generated by Github Actions."
fi

)


popd
