# On every push this script is executed
on: 
  workflow_dispatch:
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          ref: 'main'
          submodules: 'false'
      - name: build_and_deploy
        uses: DeadPoetSpoon/zola-deploy-action@master
        env:
          PAGES_BRANCH: pages
          BUILD_DIR: ./pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
